#!/usr/bin/perl

use TumblrDashboardV2;
use lib qw(/home/toshi/perl/lib);
use strict;
use utf8;
use HashDump;

my $pit_account = 'news.azwad.com';
#my $pit_account = 'tumblr.azwad.com';
#my $pit_account = 'liquige.tumblr.com';

my $limit = 20;
my $offset = 0;
my $since_id = 26893448332;
my $type = 'text';
my $reblog_info = 'True';
my $notes_info = 'True';


my $td = TumblrDashboardV2->new($pit_account);


#for ($offset = 0; $offset <= $max; $offset += $num){
#	print "offset = ". $offset ." num = ". $num . "\n";
	my %opt = (
		'limit'				=> $limit,
		'offset'			=> $offset,
		'since_id'		=> $since_id,
		'type'				=> $type,
		'reblog_info'	=> $reblog_info,
		'note_info'		=> $notes_info,
	);
	$td->set_option(%opt);
my $res  = $td->get;

#}
my $res2 = $td->get_hash;

HashDump->load($res2);

